FROM tomcat:8-jre11-slim

LABEL "Project"="Vprofile"
LABEL "Author"="Kumar raj"

RUN rm -rf /usr/local/tomcat/webapps/*
COPY vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh","run"]
WORKDIR /usr/local/tomcat/
volume /usr/local/tomcat/webapps