version: "3"  # optional since v1.27.0
services:
  vprodb:
    image: kumarrajdev5/db:latest
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vpropassdb

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: kumarrajdev5/app:v3
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    image: kumarrajdev5/web:v2
    ports:
      - "80:80"

volumes:
  vprodbdata: { }
  vproappdata: { }